apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wordpress-pvc
    labels:
        app: wordpress
spec:
    storageClassName: local-path
    resources:
        requests:
            storage: 6Gi
    accessModes:
        - ReadWriteOnce
