apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  labels:
    name: wordpress-ingress
spec:
  rules:
    - host: wordpress.app.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: wordpress-svc
                port:
                  number: 80
