apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: small
    annotations:
        storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
reclaimPolicy: Retain # default value is Delete
volumeBindingMode: WaitForFirstConsumer
